GerenciadorDeTarefas.Web/Controllers/TarefaController.cs
using GerenciadorDeTarefas.Domain.Tarefas;
using GerenciadorDeTarefas.Domain.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace GerenciadorDeTarefas.Web.Controllers;

public class TarefaController : Controller
{
    private readonly ITarefaService _tarefaService;

    public TarefaController(ITarefaService tarefaService) => _tarefaService = tarefaService;

    public async Task<IActionResult> Index(TarefaFilter filter)
    {
        var tarefas = await _tarefaService.Listar();

        tarefas = FiltrarTarefas(filter, tarefas);

        ViewBag.Tarefas = tarefas;
        return View(filter);
    }

    public async Task<IActionResult> Create(Guid id)
    {
        var tarefa = await _tarefaService.BuscarPorId(id);
        return View(tarefa);
    }

    public async Task<IActionResult> Lixeira()
    {
        var tarefas = await _tarefaService.Listar();
        tarefas = tarefas.Where(t => t.ExcluidoEm.HasValue).ToList();

        return View(tarefas);
    }

    private List<Tarefa> FiltrarTarefas(TarefaFilter filter, List<Tarefa> tarefas)
    {
        tarefas = tarefas.Where(q => !q.ExcluidoEm.HasValue).ToList();

        if (!string.IsNullOrWhiteSpace(filter.Search))
        {
            tarefas = tarefas
                .Where(q => q.Titulo.Contains(filter.Search, StringComparison.OrdinalIgnoreCase) ||
                            q.Descricao.Contains(filter.Search, StringComparison.OrdinalIgnoreCase) ||
                            q.Status.Contains(filter.Search, StringComparison.OrdinalIgnoreCase))
                .ToList();
        }

        switch (filter.Predicate)
        {
            case "Titulo":
                tarefas = filter.Decrescente
                    ? tarefas.OrderByDescending(q => q.Titulo).ToList()
                    : tarefas.OrderBy(q => q.Titulo).ToList();
                break;
            case "Descricao":
                tarefas = filter.Decrescente
                    ? tarefas.OrderByDescending(q => q.Descricao).ToList()
                    : tarefas.OrderBy(q => q.Descricao).ToList();
                break;
            case "DataDeCriacao":
                tarefas = filter.Decrescente
                    ? tarefas.OrderByDescending(q => q.DataDeCriacao).ToList()
                    : tarefas.OrderBy(q => q.DataDeCriacao).ToList();
                break;
            case "Status":
                tarefas = filter.Decrescente
                    ? tarefas.OrderByDescending(q => q.Status).ToList()
                    : tarefas.OrderBy(q => q.Status).ToList();
                break;
        }

        return tarefas;
    }

}

GerenciadorDeTarefas.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Gerenciador de tarefas</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/icons/favicon-16x16.png">
    <link rel="manifest" href="/icons/site.webmanifest">
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GerenciadorDeTarefas.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar app-navbar py-2">
            <div class="container d-flex align-items-center flex-sm-row flex-column gap-2">
                <a href="@Url.Action("Index", "Tarefa")"
                   class="mx-auto d-flex align-items-center gap-2 text-decoration-none">

                    <img src="/imagens/logo.svg"
                         alt="Logo"
                         class="app-logo">

                    <h4 class="text-white mb-0">Gerenciador de Tarefas</h4>
                </a>
                <a href="@Url.Action("Lixeira", "Tarefa")"
                   class="text-white text-decoration-none small"
                   title="Visualizar tarefas excluídas">
                    🗑 Lixeira
                </a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="py-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - Gerenciador de tarefas
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GerenciadorDeTarefas.Web/Views/Tarefa/Create.cshtml
@using GerenciadorDeTarefas.Domain.ViewModels
@model TarefaViewModel

<form action="/api/Tarefas" method="post" class="row g-3">


    <input asp-for="Id" type="hidden" />
    <input asp-for="DataDeCriacao" type="hidden" />

    <div class="col-md-6">
        <label asp-for="Titulo" class="fw-semibold">Título</label>
        <input asp-for="Titulo" class="form-control" required />
    </div>

    <div class="col-md-6">
        <label asp-for="Status" class="fw-semibold"></label>
        <input asp-for="Status" class="form-control" required/>
    </div>

    <div class="col-12">
        <label asp-for="Descricao" class="fw-semibold">Descrição</label>
        <textarea rows="3" asp-for="Descricao" class="form-control" required></textarea>
    </div>


    <div class="justify-content-end d-flex gap-2">

        <a href="@Url.Action("Index")" class="btn btn-secondary">
            Voltar
        </a>

        <button type="submit" class="btn btn-primary">
            Salvar
        </button>
    </div>
</form>

GerenciadorDeTarefas.Web/Views/Tarefa/Index.cshtml
@using GerenciadorDeTarefas.Domain.Tarefas
@using GerenciadorDeTarefas.Domain.ViewModels
@model TarefaFilter

@{
    List<Tarefa> tarefas = ViewBag.Tarefas;
}


<div class="d-flex justify-content-between flex-sm-row gap-2 flex-column">
    <div>

        <h3>Listagem de tarefas</h3>
    </div>

    <div class="text-end">
        <a href="@Url.Action("Create")" class="btn btn-primary"> Adicionar</a>
    </div>
</div>


<form action="" method="get" class="row g-3">
    <div class="col-lg-5">
        <label asp-for="Search" class="fw-semibold">Buscar</label>
        <input asp-for="Search" class="form-control" placeholder="Busque por título, descrição ou status" />
    </div>

    <div class="col-lg-4">
        <label asp-for="Predicate" name="Predicate" class="fw-semibold">Selecione a ordenação</label>
        <select asp-for="Predicate" class="form-select" name="Predicate">
            <option value="Titulo">Titulo</option>
            <option value="Descricao">Descrição</option>
            <option value="Status">Status</option>
            <option value="DataDeCriacao">Data de criação</option>
        </select>
    </div>

    <div class="col-lg-3 align-content-end">
        <div class="form-check">
            <label asp-for="Decrescente" class="fw-semibold">Ordem decrescente</label>
            <input class="form-check-input" type="checkbox" asp-for="Decrescente" />
        </div>
    </div>


    <div class="col-12 text-end">
        <button type="submit" class="btn btn-primary">
            Filtrar
        </button>
    </div>
</form>

@if (!tarefas.Any())
{
    <div class="alert alert-info mt-3">
        Nenhuma tarefa encontrada
    </div>
}
else
{
    <div class="table-responsive-lg mt-3">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Título</th>
                    <th scope="col">Descrição</th>
                    <th scope="col">Status</th>
                    <th scope="col"> </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var tarefa in tarefas)
                {
                    <tr>
                        <th>@tarefa.Titulo</th>
                        <th>@tarefa.Descricao</th>
                        <th><span class="badge bg-secondary">@tarefa.Status</span></th>
                        <th class="text-end">
                            <div class="dropdown">
                                <button class="btn border-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <div class="icon-ellipsis-horizontal"></div>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="@Url.Action("Create", new { Id = tarefa.Id })">Editar</a></li>
                                    <li><hr class="dropdown-divider" /></li>
                                    <li>
                                        <form action="/api/Tarefas/Remover/@tarefa.Id" method="post">
                                            <button type="submit"
                                                    class="btn dropdown-item text-danger"
                                                    onclick="return confirm('A tarefa será movida para a lixeira. Continuar?')">
                                                Excluir
                                            </button>
                                        </form>

                                    </li>
                                </ul>
                            </div>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

GerenciadorDeTarefas.Web/Views/Tarefa/Lixeira.cshtml
@using GerenciadorDeTarefas.Domain.Tarefas
@model List<Tarefa>

<div class="container mt-4">

    <div class="d-flex justify-content-between align-items-center mb-4">
        <h3>Lixeira</h3>

        <a href="@Url.Action("Index", "Tarefa")" class="btn btn-secondary">
            Voltar
        </a>
    </div>

    @if (!Model.Any())
    {
        <div class="alert alert-info">
            Nenhuma tarefa na lixeira
        </div>
    }
    else
    {
        <div class="table-responsive">
            <table class="table table-hover align-middle">
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Descrição</th>
                        <th>Status</th>
                        <th>Excluído em</th>
                        <th class="text-end">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var tarefa in Model)
                    {
                        <tr>
                            <td>@tarefa.Titulo</td>
                            <td>@tarefa.Descricao</td>
                            <th><span class="badge bg-secondary">@tarefa.Status</span></th>
                            <td>@tarefa.ExcluidoEm!.Value.ToString("dd/MM/yyyy")</td>
                            <td class="text-end d-flex justify-content-end gap-2">

                                <form action="/api/Tarefas/Restaurar/@tarefa.Id" method="post">
                                    <button type="submit" class="btn btn-sm btn-success">
                                        Restaurar
                                    </button>
                                </form>

                                <form action="/api/Tarefas/RemoverDefinitivamente/@tarefa.Id" method="post">
                                    <button onclick="return confirm('Tem certeza que deseja remover definitivamente?')" type="submit" class="btn btn-sm btn-danger">
                                        Excluir
                                    </button>
                                </form>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
</div>